name: NBA 2k Locker Codes
on:
  schedule:
    - cron: '0 7,19 * * *'
jobs:
  collector:
    name: NBA 2k locker codes collector
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 
    - name: Install dependencies
      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Running app with 24 version
      run: python 2k.py 24
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_2K_BOT_TOKEN }}
        TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
        NBA2K_JSON: ${{ secrets.NBA2K_JSON }}
        LOCKERCODES_HOST: ${{ secrets.LOCKERCODES_HOST }}
        LOCKERCODES_PATH: ${{ secrets.LOCKERCODES_PATH }}
