name: NBA 2k Locker Codes
on:
  schedule:
    - cron: '0 7,19 * * *'
jobs:
  collector:
    name: NBA 2k locker codes collector
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install dependencies
      run: go get -v
    - name: Running app with 24 version
      run: go run main.go -version 24
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_2K_BOT_TOKEN }}
        TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
        NBA2K_JSON: ${{ secrets.NBA2K_JSON }}
        LOCKERCODES_HOST: ${{ secrets.LOCKERCODES_HOST }}
        LOCKERCODES_PATH: ${{ secrets.LOCKERCODES_PATH }}
